services:
  web:
    build: .
    restart: always
    environment:
      - SECRETS=./secrets
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    # healthcheck:
    #   test: docker-healthcheck
    #   interval: 5s
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - snippetbox:/var/lib/mysql
volumes:
  snippetbox:
